site_name: HTML и CSS
site_url: https://hcdev.ru/
site_description: Справочник web-разработчика с примерами кода - HTML, CSS
site_author: hcdev.ru
copyright: (C) 2021, Справочник разработчика HTML и CSS с примерами кода

repo_name: 'Справочник на Github'
repo_url: 'https://github.com/xsltdev/hcdev.ru'

theme:
    name: material
    custom_dir: overrides
    include_search_page: false
    search_index_only: true
    palette:
        - scheme: default
          primary: red
          accent: red
          toggle:
              icon: material/toggle-switch-off-outline
              name: Переключиться на темную тему
        - scheme: slate
          primary: red
          accent: red
          toggle:
              icon: material/toggle-switch
              name: Переключиться на светлую тему
    language: ru
    features:
        - navigation.tabs
        - navigation.tracking
    favicon: html.svg
    logo: html.svg

extra:
    generator: false
    social:
        - icon: fontawesome/brands/telegram
          link: https://t.me/hcdev_ru
          name: Группа в Telegram

#google_analytics:
#    - UA-34215161-1
#    - auto

markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: false
          linenums: false
    - toc:
          permalink: true
    - pymdownx.extra
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.superfences

plugins:
    - search:
          lang:
              - ru
              - en
    - awesome-pages
    - section-index
    - social

extra_javascript:
    - 'https://cdn.jsdelivr.net/gh/ireade/caniuse-embed/caniuse-embed.min.js'

extra_css:
    - '/assets/stylesheets/styles.css'
